### POST PRICE
POST http://localhost:3000/price/price
Content-Type: application/json

{
    "_amount" : 17.00,
    "_idKindPrice":"617ef5964ce8a3345cdc6709",
    "_idProduct":"618148527e5d783da013a297"
}

### POST PRICE
POST http://localhost:3000/price/price
Content-Type: application/json

{
    "_amount" : 17.00,
    "_idKindPrice":"617ef5964ce8a3345cdc6709",
    "_idProduct":"618148547e5d783da013a29a"
}

### POST PRICE
POST http://localhost:3000/price/price
Content-Type: application/json

{
    "_amount" : 15.00,
    "_idKindPrice":"617ef5964ce8a3345cdc6709",
    "_idProduct":"61803f573bb49333807ba04c"
}

### POST MULTIPLE PRICE
POST http://localhost:3000/price/price/multiple
Content-Type: application/json

{
    "_productIds": ["x","y"],
    "_prices":[
        {
             "_id":"a",
            "_amount":0
        },
        {
            "_id":"b",
            "_amount":0
        }
    ]
}

### PUT PRICE BY ID PRODUCT AND ID KIND PRICE
### http://localhost:3000/price/price/updateById/:_idPrice
PUT http://localhost:3000/price/price/udpateById/
Content-Type: application/json

{
    "_amount":6
}

### GET FULL PRICES BY _IDPRODUCT
### http://localhost:3000/price/price/readFullPricesByIdProduct/:_idProduct
GET http://localhost:3000/price/price/readFullPricesByIdProduct/6170b9f50bede11c4cd302b1

### GET PRICE
GET http://localhost:3000/price/price

### GET FULL PRICE
GET http://localhost:3000/price/price/full

<<<<<   DATA TESTING   >>>>>
    <   KindPrice = menor  >
    "_amount" : 20,
    "_idKindPrice":"",
    "_idProduct":""

    <   KindPrice = mayor  >
    "_amount" : 18,
    "_idKindPrice":"",
    "_idProduct":""

    <   KindPrice = priviligiado  >
    <   priviligiado no se basa en ninguno
    de los tipso de precios definidos por un
    liminte inferior y superior, no importa 
    la cantidad, aplica cualquier cantidad  >
    "_amount" : 18,
    "_idKindPrice":"",
    "_idProduct":""