### POST ESTART_SALE_ORDER
POST http://localhost:3000/saleOrder/saleOrder
Content-Type: application/json

{
}

### DELETE ONE SALE ORDER
### DELETE http://localhost:3000/saleOrder/saleOrder/deleteOne/_idSaleOrder
DELETE http://localhost:3000/saleOrder/saleOrder/deleteOne/614a5abb7ba42225c4ef9281

### PUT TAKE_SALE_ORDER
PUT  http://localhost:3000/saleOrder/saleOrder/take
Content-Type: application/json

{
    "_id": "6128af108084fc1a80a4ffb7",
    "_idClient": "61249718145286317ca1632a",
    "_idSeller": "6127315d92f54b32dc73b20f"
}

### GET NON_PAID_SALE_ORDERS
GET http://localhost:3000/saleOrder/saleOrder/nonPaid

### PUT COLLECT_SALE_ORDER
PUT  http://localhost:3000/saleOrder/saleOrder/collect
Content-Type: application/json

{
    "_id": "6128b03ebad9ba3c1883c118",
    "_idDebtCollector": "6127315d92f54b32dc73b20f"
}

### GET PAID_SAIL_ORDERS
GET http://localhost:3000/saleOrder/saleOrder/paid

### PUT DELIVER SALE ORDER
PUT  http://localhost:3000/saleOrder/saleOrder/deliver
Content-Type: application/json

{
    "_id": "6128b03ebad9ba3c1883c118",
    "_idDeliver": "6127315d92f54b32dc73b20f"
}

### GET SALE ORDER WITH STATUS
GET http://localhost:3000/saleOrder/saleOrder/readWithStatus

### GET SAIL_ORDERS
GET http://localhost:3000/saleOrder/saleOrder

### GET SAIL_ORDERS
#GET http://localhost:3000/saleOrder/saleOrder/readById/:_idSaleOrder
GET http://localhost:3000/saleOrder/saleOrder/readById/6174d9578d450a354080ff27


### GET DAILY SALES
#POST http://localhost:3000/saleOrder/saleOrder/dailySales
POST http://localhost:3000/saleOrder/saleOrder/dailySales
Content-Type: application/json

{
    "_dateStart": "Wed Nov 03 2021 06:31:23 GMT-0600 (hora estándar central)",
    "_dateEnd": "Wed Nov 03 2021 23:31:23 GMT-0600 (hora estándar central)"
}